### ISSUE TITLE
Questions/machine_learning_q1 답변 이슈

### ISSUE THREAD

**Issue by seung-woo-ryu** [kozistr/ML-Study#1]
Questions/machine_learning_q1.md 질문 중

Q) CNN이 MLP보다좋은이유는?
A) MLP 보다 CNN 이 더 많은 파라메터를 가실 수 있어 표현력이 더 좋다.

위와 같이 답해주셨는데 CNN,MLP 단어 위치를 반대로 해야지 맞는 표현 아닌가요?

**Comment by kozistr** [comment]
안녕하세요. 꽤 오래된 repo인데, issue 남겨주셔서 감사합니다!

아마 당시에 적고 싶었던 의도는 비슷한 (trainable) parameters 수 대비 단순 CNN operation이 fully connected (dense) operation 보다, (image domain 가정)에서 표현력과 도메인에 더 어울리는 연산을 해서 좋다 할 수 있다를 설명하고 싶었던 것 같습니다!

문제 요지엔 조금 빗나갈 순 있지만, 답변을 더 보충해 보자면, 
케바케로 어떤 domain이나 task, 목적 또는 architecture design에 따라서 CNN이나 dense 연산이 상대적으로 좋을 수도 좋지 못할 수도 있을 듯 합니다! 최근엔 mlp-based (CNN-free) vision model 들이 CNN based model 과 comparable 하거나 outperform 한 성능을 보여주고 있어서, 요런 점들을 고려하면 저 질문도 이젠 옛말일 듯합니다 ㅎㅎ

레포에 관심 가져 주셔서 감사합니다!

**Comment by seung-woo-ryu** [comment]
좋은 답변 감사합니다!!!ㅎㅎㅎ
